# Generated by Django 3.0.8 on 2020-07-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todopost',
            options={'ordering': ['-deadline']},
        ),
    ]
